alumno := Alumno new.
docente := Docente new.

alumno nombre: 'Delfina'.
alumno genero: 'Femenino'.
alumno fechaNacimiento: (Date fromString: '21/11/2006').
alumno soltero.
docente nombre: 'Carlos'.
docente genero: 'Masculino'.
docente fechaNacimiento: (Date fromString: '29/07/1956').
docente casado.

alumno fechaInscripcion: (Date fromString: '12/03/2021').
alumno carrera: 'Ingeniería en Sistemas de Información'.
alumno fechaInscripcion.
alumno carrera.

docente fechaAlta: (Date fromString: '12/08/1993').
docente cargo: 'Ayudante de primera'.
docente fechaAlta.
docente cargo .

alumno diasEstudiando.
alumno saludar .
docente antiguedad.
docente saludar.
