4- Dentro de la clase Number escribir los métodos que representen los siguientes comportamientos:
       a) Realizar la suma de los primeros N enteros (N es el objeto receptor).
|n|
n := (Prompter prompt: 'ingrese un entero ' ) asNumber.
MessageBox notify: n sumaNenteros printString

       b) Modificar el método definido en a) para realizar la suma de los recíprocos de los primeros N enteros.
n := (Prompter prompt: 'ingrese un entero') asNumber.
MessageBox notify: n sumaNreciprocos printString.

       c) Modificar el método definido en a) para realizar la suma de 1 / ( x + 1) para los primeros N enteros.
n := (Prompter prompt: 'ingrese un entero' ) asNumber.
MessageBox notify: n sumaNreciprocosMasUno printString.

