6- Crear la clase Circunferencia y los métodos necesarios para calcular y mostrar la longitud de la circunferencia y el área del círculo por ella definido, teniendo como único dato el radio de la misma.

|cir|
Circunferencia asignaPi.
cir := Circunferencia new.
cir iRadio.
MessageBox notify:  cir calcLongitud printString caption: 'La Longitud de la circunferencia es: '.
MessageBox notify: cir calcArea printString caption: 'El Area de la circunferencia es: '.