materia := Materia new.
materia nombre: 'Fisica'.
materia anioCursado: 1.
materia horario: 'Lunes de 10:30 a 13:10'.
materia nota: 8.

alumno := Alumno new.
alumno materia.
alumno materia: materia.
alumno materia.

alumno materia nota.

al2 := Alumno new.
al2 inicializa.
alumno inicializa.

alumno inscribirEn: materia.
mat2 := Materia new.
mat2 nombre: 'Algebra'.
mat2 anioCursado: 1.
mat2 horario: 'Miercoles de 18:30 a 21:30'.
mat2 nota: 6.
alumno inscribirEn: mat2.

alumno materiasCursando.
alumno promedio.

alumno asignarNota: 4 a: 'Fisica'.
alumno promedio.