 2- Utilizando los métodos de la clase Number, escribir las expresiones que permitan calcular:
       a) el arcotangente de Pi
180 degreesToRadians arcTan					1.2626272556789118

       b) el cubo de 25
25 raisedTo: 3								15625

       d) el cubo del seno de 45 grados
45 degreesToRadians sin raisedTo: 3			0.3535533905932737

       e) la inversa del coseno de Pi
180 degreesToRadians cos raisedTo: -1			-1.0

       f) el entero superior más próximo a 35.8
35.8 ceiling								36

       g) el redondeo de 35.8
35.8 rounded								36

       h) el redondeo de 100 veces el seno de 33 grados
(33 degreesToRadians sin * 100) rounded		54

       j) el mayor valor entre el factorial de 3 y la raíz cúbica de 64
3 factorial max: ( 64 raisedTo: 1/3)				6
