1- Dados los siguientes mensajes:
       1.a) Clasificarlos en mensajes unarios, binarios o de palabra clave.
       1.b) Elegir un mensaje de cada grupo y analizar su estructura identificando
            objeto receptor, método y argumentos.
       1.c) Evaluar cada mensaje con Display it y obtener el resultado.
       1.d) Indicar a qué clase pertenece el método y qué hace. // Faltaria este ejercicio
       
       7 max: 5 7			
Palabra clave, 7 es receptor, max: es el metodo y 2 es el argumento
       5 max: 7 7			
Palabra clave      
       2 min: 5 2			
Palabra clave
       5 min: 2 2			
Palabra clave
       12 + 2 14			
Binario, 12 es receptor, + es el metodo y 4 es el argumento
       12 + 2.0 14.0			
Binario
       12 - 14.5 -2.5			
Binario 
       12 * 2 24			
Binario
       12 * 2.0 24.0			
Binario
       14 / 2 7			
Binario
       14 / 3 14/3			
Binario
       14 / 3.0 4.666666666666667			
Binario
       4 raisedTo: 3 64		
Palabra clave
       4 raisedToInteger: 3 64	
Palabra clave
       4 raisedTo: 0.5 2.0		
Palabra clave
       2 sqrt 1.4142135623730951			
Unario, 2 es receptor, sqrt es el metodo
       9 squared 81			
Unario
       4 even true			
Unario
       7 even false			
Unario
       2 odd false			
Unario
       3 odd true			
Unario
       -3 negative true		
Unario
       3 negative false		
Unario
       -3 positive false		
Unario
       3 positive true			
Unario
       4 sign 1			
Unario
       -4 sign -1			
Unario
       2.3 ceiling 3			
Unario
       -2.3 ceiling -2		
Unario
       2.3 truncated 2		
Unario
       -2.3 truncated -2		
Unario
       2.3 rounded 2		
Unario
       2.6 rounded 3		
Unario
       7 reciprocal 1/7		
Unario
       ( 3 / 8 ) reciprocal 8/3	
Unario, el de adentro binario 
       3 / 8 reciprocal 24		
Unario
       1 exp 2.718281828459045			
Unario
       1 ln 0.0				
Unario
       2 log: 2 1.0			
Binario
       4 factorial 24			
Unario
       16 gcd: 6 2			
Palabra clave
       16 lcm: 6 48			
Palabra clave
       12 asFloat	12.0		
Unario
       12.0 asInteger	12	
Unario
       ( 3 / 4 ) denominator 4 
Binario
       ( 3 / 4 ) numerator 3	
Binario
       ( 3 / 4 ) asFloat 0.75		
Binario
       ( 3 / 4 ) truncated 0	
Binario
       65 asCharacter A		
Unario
       Character value: 65 A	
Palabra clave
       $A asciiValue 65		
Unario
       $A isAlphaNumeric true	
Unario
       $A isDigit	false		
Unario
       $A isLetter true		
Unario
       $2 isDigit	true		
Unario
       $2 isLetter false		
Unario
       $G isLowerCase false	
Unario
       $g isLowerCase true	
Unario
       $G isUpperCase true	
Unario
       $g isUpperCase false	
Unario
       $; isSeparator false		
Unario
       $  isSeparator	true
Unario
       $a isVowel true		
Unario
       $b isVowel false		
Unario
