5- Dentro de la clase String definir métodos para:
       a) Convertir las vocales de la cadena receptora en mayúsculas y las consonantes en minúsculas.
|cadena|
cadena := Prompter prompt: 'Ingrese una cadena'.
MessageBox notify: cadena convierte.

       b) Contar la cantidad de vocales dentro de la cadena receptora.
cadena := Prompter prompt: 'Ingrese una cadena'.
MessageBox notify: cadena contarVocales printString.

       c) Convertir los caracteres de la cadena receptora que están en mayúsculas a caracteres en minúsculas y viceversa.
cadena := Prompter prompt: 'Ingrese una cadena'.
MessageBox notify: cadena convertirMayusculasAMinusculas.

       d) Convertir los caracteres de la cadena receptora que ocupan una posición impar a mayúsculas y los que ocupan una posición par a minúsculas.
cadena := Prompter prompt: 'Ingrese una cadena'.
MessageBox notify: cadena convertirParImpar .
